"""add wardrobe items, extend outfit items for wardrobe source

Revision ID: 0243439f6391
Revises: 144a0cc62576
Create Date: 2026-08-14 19:00:48.769773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0243439f6391'
down_revision: Union[str, Sequence[str], None] = '144a0cc62576'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wardrobe_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=False),
    sa.Column('storage_key', sa.String(length=300), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wardrobe_items_user_id'), 'wardrobe_items', ['user_id'], unique=False)
    op.add_column('outfit_items', sa.Column('wardrobe_item_id', sa.UUID(), nullable=True))
    op.alter_column('outfit_items', 'clothing_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'outfit_items', 'wardrobe_items', ['wardrobe_item_id'], ['id'])
    op.create_check_constraint('outfit_item_exactly_one_source', 'outfit_items', '(clothing_id IS NOT NULL) != (wardrobe_item_id IS NOT NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('outfit_item_exactly_one_source', 'outfit_items', type_='check')
    op.drop_constraint(None, 'outfit_items', type_='foreignkey')
    op.alter_column('outfit_items', 'clothing_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('outfit_items', 'wardrobe_item_id')
    op.drop_index(op.f('ix_wardrobe_items_user_id'), table_name='wardrobe_items')
    op.drop_table('wardrobe_items')
    # ### end Alembic commands ###
