"""add saved outfits and outfit items

Revision ID: 144a0cc62576
Revises: c0c4dfcb5829
Create Date: 2026-08-14 18:15:37.101569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '144a0cc62576'
down_revision: Union[str, Sequence[str], None] = 'c0c4dfcb5829'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_outfits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('occasion', sa.String(length=30), nullable=True),
    sa.Column('liked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_outfits_user_id'), 'saved_outfits', ['user_id'], unique=False)
    op.create_table('outfit_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('saved_outfit_id', sa.UUID(), nullable=False),
    sa.Column('clothing_id', sa.UUID(), nullable=False),
    sa.Column('slot', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['clothing_id'], ['clothing.id'], ),
    sa.ForeignKeyConstraint(['saved_outfit_id'], ['saved_outfits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outfit_items_saved_outfit_id'), 'outfit_items', ['saved_outfit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outfit_items_saved_outfit_id'), table_name='outfit_items')
    op.drop_table('outfit_items')
    op.drop_index(op.f('ix_saved_outfits_user_id'), table_name='saved_outfits')
    op.drop_table('saved_outfits')
    # ### end Alembic commands ###
