"""cascade delete profile tables on user delete

Revision ID: caedd91ac305
Revises: db6fd121aa77
Create Date: 2026-08-14 14:28:51.992787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caedd91ac305'
down_revision: Union[str, Sequence[str], None] = 'db6fd121aa77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('body_measurements_user_id_fkey'), 'body_measurements', type_='foreignkey')
    op.create_foreign_key(None, 'body_measurements', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('style_preferences_user_id_fkey'), 'style_preferences', type_='foreignkey')
    op.create_foreign_key(None, 'style_preferences', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_profiles_user_id_fkey'), 'user_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'user_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('user_profiles_user_id_fkey'), 'user_profiles', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'style_preferences', type_='foreignkey')
    op.create_foreign_key(op.f('style_preferences_user_id_fkey'), 'style_preferences', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'body_measurements', type_='foreignkey')
    op.create_foreign_key(op.f('body_measurements_user_id_fkey'), 'body_measurements', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
