"""add user profile, body measurement, style preference tables

Revision ID: db6fd121aa77
Revises: 2a5782a0fcca
Create Date: 2026-08-14 14:06:56.733341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db6fd121aa77'
down_revision: Union[str, Sequence[str], None] = '2a5782a0fcca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_measurements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('usual_shirt_size', sa.String(length=10), nullable=True),
    sa.Column('usual_pants_size', sa.String(length=10), nullable=True),
    sa.Column('usual_dress_size', sa.String(length=10), nullable=True),
    sa.Column('chest_cm', sa.Float(), nullable=True),
    sa.Column('waist_cm', sa.Float(), nullable=True),
    sa.Column('hip_cm', sa.Float(), nullable=True),
    sa.Column('shoulder_cm', sa.Float(), nullable=True),
    sa.Column('inseam_cm', sa.Float(), nullable=True),
    sa.Column('arm_length_cm', sa.Float(), nullable=True),
    sa.Column('leg_length_cm', sa.Float(), nullable=True),
    sa.Column('foot_size', sa.Float(), nullable=True),
    sa.Column('fit_preference', sa.String(length=20), nullable=True),
    sa.Column('body_shape', sa.String(length=30), nullable=True),
    sa.Column('ai_estimated', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_body_measurements_user_id'), 'body_measurements', ['user_id'], unique=True)
    op.create_table('style_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('favorite_colors', sa.JSON(), nullable=False),
    sa.Column('color_group', sa.String(length=20), nullable=True),
    sa.Column('styles', sa.JSON(), nullable=False),
    sa.Column('occasions', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_style_preferences_user_id'), 'style_preferences', ['user_id'], unique=True)
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('age_range', sa.String(length=20), nullable=True),
    sa.Column('gender_preference', sa.String(length=50), nullable=True),
    sa.Column('country_region', sa.String(length=100), nullable=True),
    sa.Column('measurement_system', sa.String(length=10), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_style_preferences_user_id'), table_name='style_preferences')
    op.drop_table('style_preferences')
    op.drop_index(op.f('ix_body_measurements_user_id'), table_name='body_measurements')
    op.drop_table('body_measurements')
    # ### end Alembic commands ###
