"""add clothing catalog and size chart tables

Revision ID: ece750b3beb4
Revises: caedd91ac305
Create Date: 2026-08-14 15:09:15.022669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ece750b3beb4'
down_revision: Union[str, Sequence[str], None] = 'caedd91ac305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('size_charts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clothing',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('primary_color', sa.String(length=30), nullable=False),
    sa.Column('available_colors', sa.JSON(), nullable=False),
    sa.Column('material', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('product_url', sa.String(length=500), nullable=True),
    sa.Column('affiliate_url', sa.String(length=500), nullable=True),
    sa.Column('size_chart_id', sa.UUID(), nullable=True),
    sa.Column('fit_type', sa.String(length=20), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['size_chart_id'], ['size_charts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clothing_category'), 'clothing', ['category'], unique=False)
    op.create_table('clothing_sizes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('size_chart_id', sa.UUID(), nullable=False),
    sa.Column('size_label', sa.String(length=10), nullable=False),
    sa.Column('chest_cm', sa.Float(), nullable=True),
    sa.Column('waist_cm', sa.Float(), nullable=True),
    sa.Column('hip_cm', sa.Float(), nullable=True),
    sa.Column('length_cm', sa.Float(), nullable=True),
    sa.Column('stock_qty', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['size_chart_id'], ['size_charts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clothing_sizes_size_chart_id'), 'clothing_sizes', ['size_chart_id'], unique=False)
    op.create_table('clothing_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clothing_id', sa.UUID(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clothing_id'], ['clothing.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clothing_images_clothing_id'), 'clothing_images', ['clothing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clothing_images_clothing_id'), table_name='clothing_images')
    op.drop_table('clothing_images')
    op.drop_index(op.f('ix_clothing_sizes_size_chart_id'), table_name='clothing_sizes')
    op.drop_table('clothing_sizes')
    op.drop_index(op.f('ix_clothing_category'), table_name='clothing')
    op.drop_table('clothing')
    op.drop_table('size_charts')
    # ### end Alembic commands ###
